name: Build and deploy container app to Azure Web App - dpc-container-app

on:
  push:
    branches:
      - enh/1/docker
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Tree view
      run: |
          ls -la
          sudo apt-get install -y tree
          tree .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DH_username }}
        password: ${{ secrets.DH_password }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: rohantiger/demo1:v1
        file: ./dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dpc-container-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_38515c822ae34eff8243ac3ec0c5fe43 }}
        images: 'abilashravita/dpc-webapp:${{ github.sha }}'